spring:
  application:
    name: backend

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 446853213781-0ni25ghs8kqp2ujur303copou64p96m6.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email



database:
    host: mysql-db
    port: 3306
    username: root
    password: root
    name: test

server:
  port: 8081

mail:
    sendgrid:
      api-key: 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
      from: mykola.chichkalenko@gmail.com


